# Generated by Django 5.1.4 on 2024-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cartitem_product_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, upload_to='products/payment'),
        ),
    ]
