# Generated by Django 5.1.4 on 2024-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='products/payment'),
        ),
    ]
